"""Evidence sanitisation, idempotency-key validation and request fingerprinting.

The one rule: original header values go on the wire, redacted copies go into evidence.
Nothing in this module ever returns or hashes a sensitive header *value*.
"""

from __future__ import annotations

import hashlib
import json
import re
from collections.abc import Iterable, Mapping
from typing import Any

from app import config

REDACTED = "***REDACTED***"

# Transport-level headers generated by Callback Inspector itself — never part of the logical request.
GENERATED_HEADERS = frozenset({"x-callback-id", "x-callback-attempt"})

IDEMPOTENCY_KEY_MAX_LENGTH = 255
# Visible ASCII + space: no control characters, no CR/LF, no non-ASCII.
_IDEMPOTENCY_KEY_RE = re.compile(rf"^[\x20-\x7e]{{1,{IDEMPOTENCY_KEY_MAX_LENGTH}}}$")


def sensitive_header_names() -> frozenset[str]:
    return config.settings.sensitive_headers


def is_sensitive(name: str, sensitive: Iterable[str] | None = None) -> bool:
    names = sensitive_header_names() if sensitive is None else sensitive
    return name.strip().lower() in names


def redact_headers(headers: Mapping[str, str] | None, sensitive: Iterable[str] | None = None) -> dict[str, str]:
    """Return a copy with every sensitive header value replaced by ``***REDACTED***`` (case-insensitive)."""
    if not headers:
        return {}
    names = sensitive_header_names() if sensitive is None else frozenset(n.lower() for n in sensitive)
    return {k: (REDACTED if k.lower() in names else v) for k, v in headers.items()}


def sensitive_values(headers: Mapping[str, str] | None) -> dict[str, str]:
    """Only the sensitive headers, keyed by lower-cased name (kept in process memory, never persisted)."""
    names = sensitive_header_names()
    return {k.lower(): v for k, v in (headers or {}).items() if k.lower() in names and v != REDACTED}


def redacted_header_names(headers: Mapping[str, str] | None) -> list[str]:
    return sorted(k for k, v in (headers or {}).items() if v == REDACTED)


class InvalidIdempotencyKey(ValueError):
    pass


def validate_idempotency_key(value: str) -> str:
    if not _IDEMPOTENCY_KEY_RE.fullmatch(value or "") or value != value.strip():
        raise InvalidIdempotencyKey(
            f"Idempotency-Key must be 1-{IDEMPOTENCY_KEY_MAX_LENGTH} printable ASCII characters "
            "without control characters or leading/trailing whitespace."
        )
    return value


def _excluded_from_fingerprint() -> frozenset[str]:
    s = config.settings
    return GENERATED_HEADERS | {s.signature_header.lower(), s.timestamp_header.lower()}


def request_fingerprint(
    *,
    destination_url: str,
    method: str,
    headers: Mapping[str, str],
    payload: Any,
    timeout_seconds: float,
) -> str:
    """Stable SHA-256 of the *logical* delivery request.

    * header names are lower-cased, keys sorted (canonical JSON);
    * generated transport headers (X-Callback-Id/-Attempt, signature, timestamp) are excluded;
    * sensitive header values are replaced by the redaction marker — the fingerprint is persisted,
      so it must not be derived from secrets. A rotated credential is therefore the *same* logical
      request, while adding/removing a sensitive header is a different one.
    """
    excluded = _excluded_from_fingerprint()
    sensitive = sensitive_header_names()
    canonical_headers = {
        k.lower(): (REDACTED if k.lower() in sensitive else v) for k, v in headers.items() if k.lower() not in excluded
    }
    doc = {
        "destination_url": destination_url,
        "method": method.upper(),
        "headers": canonical_headers,
        "payload": payload,
        "timeout_seconds": float(timeout_seconds),
    }
    canonical = json.dumps(doc, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()
